#!/bin/bash

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find itself as POSIX compliant, but you have some other shells available,
#       you can try to invoke the script with them: bash, ksh, or zsh.
#
#   (2) Now the script will assume a Bash shell. Use `chsh` to change your default
#       shell.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while
    APP_HOME=${PRG%"${PRG##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$PRG" ]
do
    PRG=$(readlink "$PRG") || exit
    [ -e "$PRG" ] || exit
done
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo "$*" >&2
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
nativewin=false
case "$(uname)" in
CYGWIN* )
    cygwin=true
    ;;
Darwin* )
    this_script_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    ;;
MINGW* )
    msys=true
    ;;
NATIVEWIN )
    nativewin=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# JAVA_OPTS handling is done directly in the exec command below

# Escape application args
save() {
    for i do printf '%s\n' "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"; done
    echo " "
}
APP_ARGS=$(save "$@")
eval "set -- $APP_ARGS"

# When using Cygwin or MSYS you need additional processing
if $cygwin; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
            -*)   false ;;                            # don't mess with options #(
            /?*)   t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                [ -e "$t" ] ;;                         #(
            *)    false ;;
            esac
        then
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        save "$arg"
    done
    args=$(save "$@")
    eval "set -- $args"
    # Let's convert again for Cygwin to mixed mode, just to be safe.
    eval "set -- $(printf '%s\n' "$args" | sed -e 's/^-/\\-/g')"
fi
if $msys; then
    APP_HOME=$(sh -c 'echo "$0" | sed -e "s,\\\\,/,g"' "$APP_HOME")
    CLASSPATH=$(sh -c 'echo "$0" | sed -e "s,\\\\,/,g"' "$CLASSPATH")

    JAVACMD=$(sh -c 'echo "$0" | sed -e "s,\\\\,/,g"' "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
            -*)   false ;;                            # don't mess with options #(
            /?*)   t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                [ -e "$t" ] ;;                         #(
            *)    false ;;
            esac
        then
            arg=$(cygpath --path --mixed "$arg")
        fi
        save "$arg"
    done
    args=$(save "$@")
    eval "set -- $args"
    # Let's convert again for Msys to mixed mode, just to be safe.
    eval "set -- $(printf '%s\n' "$args" | sed -e 's/^-/\\-/g')"
fi
if $nativewin ; then
    # Cygwin/MSYS merged with native Windows build, so pitch in native Windows paths too.
    CLASSPATH=$(cygpath --path --mixed --windows "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")
    # Now convert the arguments - kludge to limit ourselves to cmd.exe
    for arg do
        if
            case $arg in                                #(
            -*)   false ;;                            # don't mess with options #(
            /*)   t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                [ -e "$t" ] ;;                         #(
            ?:[\\/]* )  true ;;
            *)    false ;;
            esac
        then
            arg=$(cygpath --path --windows "$arg")
        fi
        save "$arg"
    done
    args=$(save "$@")
    eval "set -- $args"
fi

# Add classpath
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar:$CLASSPATH

# Now execute the Java SubWiki with the correct settings class name and arguments.
eval "exec \"$JAVACMD\" $JAVA_OPTS $DEFAULT_JVM_OPTS \
    -classpath \"$CLASSPATH\" \
    org.gradle.wrapper.GradleWrapperMain \
    \"\$@\""
